
# .github/workflows/keep-neon-alive.yml

name: Keep Neon Alive
on:
  schedule:
    # Runs every 5 minutes (GitHub's shortest interval)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  ping-neon:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Neon DB
        run: |
          curl -X GET "https://handcrafted-gamma.vercel.app/api/keep-alive"
        